### ISSUE TITLE
npm-snapshot fails on Windows with newest Node versions

### ISSUE THREAD

**Issue by bergerst** [oscard0m/npm-snapshot#17]
After fixing a CVE, it's now required to set `{ shell: true }` when spawning npm processes on Windows: https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2

I tested it locally and just adding the shell option in this line fixed the problem: https://github.com/oscard0m/npm-snapshot/blob/01a3120d7745ba5cb5549645f8b7939d04fe3b3c/bin/npm-snapshot#L59

**Comment by oscard0m** [comment]
@bergerst let me know if this solves the issue.

Thanks for taking the time for reporting this 👏🏽

**Comment by bergerst** [comment]
Yes, it does. Thank you.
